package:
  name: sorted_csv_diff
  version: 0.0.2

source:
  git_url: https://github.com/RSTZZZ/sorted_csv_dff.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - loguru

test:
  imports:
    - sorted_csv_diff

about:
  home: https://github.com/RSTZZZ/sorted_csv_dff
